title: Warframe Guides
description: A collection of Warframe Guides created by and for the Warframe Arbitrations Discord community.
theme: just-the-docs
color_scheme: dark

url: https://guide.faby.dev/Warframe-Guides

aux_links:
  Join Our Discord: http://discord.gg/PmB6qhDzUg
  
kramdown:
  hard_wrap: true

collections:
  guides:
    output: true
    permalink: /:path
  builds:

just_the_docs:
  collections:
    guides:
      name: Guides

toc:
  max_level: 2 # default: 6

defaults:
  - scope:
      path: ""
    values:
      toc: true

plugins:
  - jekyll-toc


callouts:
  important:
    title: Important
    color: yellow
  reminder:
    title: Reminder
    color: purple
  note:
    title: Note
    color: green